######################################################################
# Automatically generated by qmake (1.06c) Sun May 1 15:24:36 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += qt_mastermind.h
SOURCES += qt_mastermind.cpp
